2014-06-13 23:19:06,313 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-13 23:19:06,834 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-13 23:20:09,365 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-13 23:35:48,552 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-13 23:35:49,062 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 00:06:00,938 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 00:06:01,415 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 00:17:50,319 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 00:22:13,572 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 00:23:13,461 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 00:23:13,980 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 00:24:46,894 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 00:25:08,460 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 00:25:33,190 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 00:26:02,101 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 00:32:52,664 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 00:33:06,875 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:06:30,540 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:06:31,046 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:16:49,102 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:16:49,630 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:19:24,775 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:19:28,325 ERROR: Exception on / [GET] [in C:\Python27\lib\site-packages\flask\app.py:1306]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\views.py", line 50, in index
    posts = posts)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 125, in render_template
    context, ctx.app)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 107, in _render
    rv = template.render(context)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\templates\index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\templates\base.html", line 41, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\templates\index.html", line 27, in block "content"
    {% include 'post.html' %}
  File "C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\templates\post.html", line 5, in top-level template code
    <div><a href="{{ url_for('delete', id=post.id) }}">{{_('Delete')}}</a></div>
UndefinedError: '_' is undefined
2014-06-14 13:19:33,470 ERROR: Exception on / [GET] [in C:\Python27\lib\site-packages\flask\app.py:1306]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\views.py", line 50, in index
    posts = posts)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 125, in render_template
    context, ctx.app)
  File "C:\Python27\lib\site-packages\flask\templating.py", line 107, in _render
    rv = template.render(context)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\templates\index.html", line 2, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\templates\base.html", line 41, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\templates\index.html", line 27, in block "content"
    {% include 'post.html' %}
  File "C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\templates\post.html", line 5, in top-level template code
    <div><a href="{{ url_for('delete', id=post.id) }}">{{_('Delete')}}</a></div>
UndefinedError: '_' is undefined
2014-06-14 13:19:51,108 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:19:51,638 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:20:50,315 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:20:54,957 ERROR: Exception on /delete/4 [GET] [in C:\Python27\lib\site-packages\flask\app.py:1306]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Python27\lib\site-packages\flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\views.py", line 185, in delete
    db.session.delete(post)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\scoping.py", line 114, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 1400, in delete
    self._attach(state)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 1656, in _attach
    state.session_id, self.hash_key))
InvalidRequestError: Object '<Post at 0x381f3f0>' is already attached to session '1' (this is '6')
2014-06-14 13:38:49,503 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:38:50,032 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:41:29,177 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:41:52,831 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:47:28,236 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:47:30,849 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:48:04,292 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:48:27,884 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 13:48:28,404 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
2014-06-14 14:33:28,457 INFO: LiBlog startup [in C:\Users\Grant\Documents\GitHub\LithiumBlogging\app\__init__.py:36]
